language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
 
before_install:
 - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
 - composer install --prefer-source

script:
 - phpunit --configuration tests/phpunit.xml.dist --coverage-clover build/clover.xml

notifications:
 email:
  - chuck@manchuck.com

after_script:
 - vendor/bin/coveralls -c .coveralls.yml -vvv

